kind: pipeline
name: default

steps:
  
- name: Deploy
  image: alpine
  commands:
  - apk update
  - apk add npm curl jq
  - npm install -g markdownlint-cli 
  - npm install -g markdown-pdf --ignore-scripts
  - markdown-pdf -o README.pdf -f Letter -r portrait README.md
  - markdown-pdf -o lf-glossary.pdf -f Letter -r portrait lf-glossary.md
