kind: pipeline
name: default

steps:
  
- name: Deploy
  image: ubuntu
  commands:
  - apt-get update
  - apt-get install -y npm curl jq libfontconfig1
  - npm install -g markdownlint-cli 
  - npm install -g markdown-pdf
  - markdown-pdf -o README.pdf -f Letter -r portrait README.md
  - markdown-pdf -o lf-glossary.pdf -f Letter -r portrait lf-glossary.md
